### ISSUE TITLE
no fixed version of self-service-password

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [tiredofit/docker-self-service-password#10]
I will fordward here as plain as possible some concerns of integrating your container:
https://github.com/zokradonh/kopano-docker/pull/70#discussion_r245222884

I assume that fetching a specific release from should be easily modified by changing this line:
https://github.com/tiredofit/docker-self-service-password/blob/734837f712c8903ce0f97c1a74a44c555e403128/install/etc/s6/services/10-nginx/run#L86
to
```git clone --depth 1 --branch v1.3 --single-branch https://github.com/ltb-project/self-service-password /www/ssp```

Nevertheless, the second part, the mounting of the service itself in a persistent storage is more difficult in my eyes. We could surely omit the persistent story if this service is stateless and all configuration is passed by the docker env vars. If the service is not stateless, we have to keep the config and should provide update mechanisms when a new ssp version drops in via container update. Do you know about this detail, or should we invite directly https://github.com/ltb-project/self-service-password developers to the discussion?

best,
Christian

**Comment by fbartels** [comment]
Hi, I am the one that raised the "concerns". Just looking through this project for me it actually already feels quite stateless so just rebuilding the config when replacing the container should already work quite good,

The `v1.3` in above command also be queried automatically with the following command: `git ls-remote --refs --tags https://github.com/ltb-project/self-service-password | sort -t '/' -k 3 -V | awk -F/ '{ print $3 }' | tail -1`. Afterwards this would then only need to be tagged in the docker hub.

**Comment by tiredofit** [comment]
HI, just to confirm, it is stateless as you have found with the only settings that need to be changed is the configuration file. My production image works in a different manner, where all code is embedded inside the image without the exposed volumes. It could certainly be built like that, however that would limit people from being able to customize any of the images / html templates easily. Moving the install routines into the Dockerfile is quite simple however. 

One of the reasons why I've kept it as a static release without always pulling latest release from github is the configuration file. I'm sure there is a much better way to dynamically change any of the options introduced any newer releases. At this time I've kept it to be a pure bash/sed solution, and with each point release has introduced more options to configure. It's dirty and could use some work.

I can also add another tag on Docker Hub to not use my own changelog version number (v1.3), but either a combo (1.3-2.5), or something in between.

**Comment by cguentherTUChemnitz** [comment]
Yes I would like to see the installation inside the docker build step, nevertheless I think this is not what we have to focus on. Providing a reproducible state should be the focus. I can live with the point to fetch the repo at runtime, as long as the repo keeps small. Fetching a specific release version should be the main point.

An alternative solution could be to specify the release to fetch via env var. So we could have the split between your configuration set by your image tag and the ssp release version specified by an env var.

So I propose this solution as an minimal invasive one to get the reproducible behavior.

**Comment by cguentherTUChemnitz** [comment]
Thanks for your implementation. I think this suits our needs.
