### ISSUE TITLE
Nginx start fails

### ISSUE THREAD

**Issue by parak** [tiredofit/docker-self-service-password#18]
Seems possibly related to the docker-nginx update two days ago as it was working fine before that:

`nginx: [emerg] unknown log format "specialLog" in /etc/nginx/conf.d/default.conf:6`

Dug around the code there a bit but couldn't readily find where specialLog was defined :(

**Comment by tiredofit** [comment]
Hi there. I'll push new images that reflect the changes in the upstream image, my apologies.

**Comment by parak** [comment]
Much appreciated!

**Comment by tiredofit** [comment]
New image pushed which should solve the issue!

**Comment by parak** [comment]
Looks good, thanks!
