### ISSUE TITLE
 Undefined variable: use_pwnedpasswords

### ISSUE THREAD

**Issue by missops** [tiredofit/docker-self-service-password#19]
### Prodblem: 

Notice: Undefined variable: use_pwnedpasswords in /www/ssp/index.php on line 35

which env need to set ?

**Comment by tiredofit** [comment]
That looks like a new configuration variable that's not been factored into the config file (aka new release of SSP). I will look into in a few days, unless someone beats me to it.

**Comment by javachen** [comment]
i meet this too

**Comment by joergmschulz** [comment]
see PR #24

**Comment by joergmschulz** [comment]
the current version does no longer have this issue - pls upgrade and eventually close this issue :-)
