### ISSUE TITLE
IS_BEHIND_PROXY dont work

### ISSUE THREAD

**Issue by tcs-ulli** [tiredofit/docker-self-service-password#2]

**Comment by tiredofit** [comment]
I will need more details as to your usage case to understand what the issue is...

**Comment by tcs-ulli** [comment]
As far as i see trhe Line number to remove the # in the url is wrong so the Enviroment Variable does nothing

**Comment by tiredofit** [comment]
Understood! I've just made appropriate adjustments, thanks for that!

**Comment by davehun** [comment]
regression in latest

setting the env var
      - IS_BEHIND_PROXY=true

uncomments the wrong line in /www/ssp/conf/config.inc.local.php.
leaving a file that doesn't start:

 Reset URL (if behind a reverse proxy)                                           
#$reset_url = $_SERVER['HTTP_X_FORWARDED_PROTO'] . "://" . $_SERVER['HTTP_HOST'];

it should leave
#Reset URL (if behind a reverse proxy)                                           
  $reset_url = $_SERVER['HTTP_X_FORWARDED_PROTO'] . "://" . $_SERVER['HTTP_HOST'];

**Comment by tiredofit** [comment]
Here we are again. I've done one quick fix to make it work again, and will properly repair in a few hours not relying on a line number.

**Comment by tiredofit** [comment]
New tag 3.0.1 now contains proper fix without relying on line numbers. Thanks for finding.

**Comment by davehun** [comment]
Thanks for the super fast fix 👍
