### ISSUE TITLE
Nginx Error conf in latest

### ISSUE THREAD

**Issue by nseb** [tiredofit/docker-self-service-password#22]
nginx: [emerg] unknown directive "fastcgi_buffer_suze" in /etc/nginx/nginx.conf:40

**Comment by tiredofit** [comment]
Hi there, I pushed a bad release of the upstream image yesterday, fix is incoming - just waiting for Docker Hub to rebuild all images. My apologies on the typo.

**Comment by tiredofit** [comment]
Working build back up again.
