### ISSUE TITLE
SITE_URL doesn't work

### ISSUE THREAD

**Issue by OPSTime** [tiredofit/docker-self-service-password#35]
![image](https://user-images.githubusercontent.com/5848331/88061952-c3e22000-cb9a-11ea-87ec-7b1d176e0820.png)

# configure:
```
      - IS_BEHIND_PROXY=false
      - SITE_URL=http://ssp.ops.kkaaa.com
```

**Comment by tiredofit** [comment]
Try setting `IS_BEHIND_PROXY=true` and see if you get better results.

**Comment by OPSTime** [comment]
thx
