### ISSUE TITLE
how to disable ssl for smtp

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [tiredofit/docker-self-service-password#7]
I love your up to date and lightweight container. Nevertheless, there is one configuration option which i am not able to get working.

I am running an instance of tomav/docker-mailserver with self-signed certificates. This seems to be problematic, because sending mails to this instance (here called mail) break on verifying the certificate. Alternatively i want to send the mail directly to port 25 without ssl, because this network is in a DMZ. But i am not able to disable ssl in your cotnainer for smtp. 

An outdated alternative container to yours is able to do it:
https://github.com/dtwardow/docker-ldap-self-service-password/blob/master/assets/config/msmtp/msmtprc.auth

But i was not able to adapt this configuration in your container build. So my question is, is there any way to disable ssl for smtp? How can we patch it in? I do not want to run the out-dated version of ssp only to get this config option.

best,
Christian

here is the log of the failure of the certificate verification problem. 

```
Connection: opening to mail:25, timeout=30, options=array ()
Connection: opened
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "220 mail.kopano.demo ESMTP Postfix (Debian)"
SERVER -> CLIENT: 220 mail.kopano.demo ESMTP Postfix (Debian)
CLIENT -> SERVER: EHLO kopano.demo
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "250-mail.kopano.demo"
SMTP -> get_lines(): $data is "250-mail.kopano.demo"
SMTP -> get_lines(): $str is "250-PIPELINING"
SMTP -> get_lines(): $data is "250-mail.kopano.demo250-PIPELINING"
SMTP -> get_lines(): $str is "250-SIZE 10240000"
SMTP -> get_lines(): $data is "250-mail.kopano.demo250-PIPELINING250-SIZE 10240000"
SMTP -> get_lines(): $str is "250-ETRN"
SMTP -> get_lines(): $data is "250-mail.kopano.demo250-PIPELINING250-SIZE 10240000250-ETRN"
SMTP -> get_lines(): $str is "250-STARTTLS"
SMTP -> get_lines(): $data is "250-mail.kopano.demo250-PIPELINING250-SIZE 10240000250-ETRN250-STARTTLS"
SMTP -> get_lines(): $str is "250-AUTH PLAIN LOGIN"
SMTP -> get_lines(): $data is "250-mail.kopano.demo250-PIPELINING250-SIZE 10240000250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN"
SMTP -> get_lines(): $str is "250-AUTH=PLAIN LOGIN"
SMTP -> get_lines(): $data is "250-mail.kopano.demo250-PIPELINING250-SIZE 10240000250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN250-AUTH=PLAIN LOGIN"
SMTP -> get_lines(): $str is "250-ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $data is "250-mail.kopano.demo250-PIPELINING250-SIZE 10240000250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN250-AUTH=PLAIN LOGIN250-ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $str is "250-8BITMIME"
SMTP -> get_lines(): $data is "250-mail.kopano.demo250-PIPELINING250-SIZE 10240000250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN250-AUTH=PLAIN LOGIN250-ENHANCEDSTATUSCODES250-8BITMIME"
SMTP -> get_lines(): $str is "250-DSN"
SMTP -> get_lines(): $data is "250-mail.kopano.demo250-PIPELINING250-SIZE 10240000250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN250-AUTH=PLAIN LOGIN250-ENHANCEDSTATUSCODES250-8BITMIME250-DSN"
SMTP -> get_lines(): $str is "250 SMTPUTF8"
SERVER -> CLIENT: 250-mail.kopano.demo250-PIPELINING250-SIZE 10240000250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN250-AUTH=PLAIN LOGIN250-ENHANCEDSTATUSCODES250-8BITMIME250-DSN250 SMTPUTF8
CLIENT -> SERVER: STARTTLS
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "220 2.0.0 Ready to start TLS"
SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
Connection failed. Error #2: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed [/www/ssp/lib/vendor/PHPMailer/class.smtp.php line 369]
SMTP Error: Could not connect to SMTP host.
CLIENT -> SERVER: QUIT
SMTP -> get_lines(): $data is ""
```

**Comment by tiredofit** [comment]
HI there, you should! I do the exact same thing on my networks.
Each of my servers has a companion smtp server (mine is called postfix-relay) that is very lightweight that accepts any mail from any container, and then handles all the heavy lifting sending to an actual outbound smtp server to which I use Postal. I don't believe I've released the postfix-relay image to the public, but I can certainly in short order.

This image actually has two parent containers, the most closest relative is the [docker-nginx-php-fpm image](https://github.com/tiredofit/docker-nginx-php-fpm/tree/7.1) and then the master is the [docker-alpine image](https://github.com/tiredofit/docker-alpine/tree/3.8). Have a peek at the READMEs and check out any of the SMTP options I have available for you. By default TLS _should_ be disabled, otherwise if the application itself uses its own mailing libraries, we can easily find a way to bypass it for you. 

Give a whirl with the options in the Alpine image a try while I walk through our production systems and see where things are going stray.

**Comment by tiredofit** [comment]
I've just created a new release (Docker hub is building right now) with the tag of `2.8` with a new environment variable after scanning through the LTB SSP Documentation.
`| `SMTP_AUTOTLS` | SMTP Auto TLS `true` or `false`. Defaults to `false ` |`
This looks like it's going to give you what you need. The older Docker images you are seeing don't seem to have been using the PHPMailer, which is what this one relies on. Do let me know. Also, if you need, I've just released my [postfix-relay](https://github.com/tiredofit/docker-postfix-relay) image if you find that this will help for you. I believe I also have a Postal repository as well, if you find you have problems let me know, all the repositories I have are in active use serving a 5000 user base regularly.

**Comment by cguentherTUChemnitz** [comment]
Thanks for your blazing fast response and work on my problem. It seems the last commit breaks the system, because the new variable in the configuration template is not replaced. I added therefore a pull request:
https://github.com/tiredofit/docker-self-service-password/pull/8

**Comment by tiredofit** [comment]
Nice catch. I'll tag this with a new version, and docker hub should be building a new one based on :latest right now! Let me know if this gets you going.

**Comment by cguentherTUChemnitz** [comment]
I am now able to send mails to my mail instance. Thanks for help. I will try to place soon your container as the default mechanism for password-self-service in the kopano dockerized stack:
https://github.com/zokradonh/kopano-docker

**Comment by tiredofit** [comment]
Fantastic! I will check out your stack, I am on the lookout for a Self Hosted Groupware Suite that is not Nextcloud for our Edtech institution. Always looking for something self hosted and under our control.

**Comment by aderbique** [comment]
Instead of ssl or tls, simply enter the value "none"
